### ISSUE TITLE
[PE-D][Tester E] Minor formatting error in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T11-2/tp#160]
It is possible that "Note on returning to the origin view" bullet point was included by mistake in the list of all commands as a sub-command? It appears to be inconsistent

Regardless, even if it is intended, maybe the bullet-point style should be different from the previous level?

![image.png](https://raw.githubusercontent.com/tahsinhasem/ped/main/files/5a53af51-408d-4d90-bd2c-b398ae092de1.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tahsinhasem/ped#2

**Comment by Hibeom0929** [comment]
I think it is not intended and needs to be deleted to have a consistent format.

**Comment by E0735389** [comment]
It's intended. And it does not hinder the reader.

Nevertheless, the fact that the bullet point is the same is a valid point. It's only severity.VeryLow however, since the fact that the indentation exists also serves to indicate the different level.

Will see if MarkBind have a way to distinguish the bullet point.

**Comment by E0735389** [comment]
It seems simple enough to suppress it from the table of content, so done.
