### ISSUE TITLE
Course-specific role

### ISSUE THREAD

**Issue by E0735389** [AY2324S2-CS2103T-T11-2/tp#64]
Currently, each person can only have one role. What if your TA for CS1000 is also your TA for CS2000, is taking CS3000 with you and is a student in module CS4000 for which you're teaching?

**Comment by ChillinRage** [comment]
I'm thinking of 2 possibilities:

1. Change the parsing so that you can add 2 people of the same attributes EXCEPT course. That means you can have 2 Alex Yeohs (for example) with same phone, email, address, role, and tags, but one is CS2101 and the other CS2103T. 

This can be a bit less reader friendly on the GUI side since you have cases where you can see multiple Alex Yeohs grouped together. Implementation-wise it'll be easier since I just need to change the `isSamePerson` function to account for `course.equals` instead.


2. Change it so that one contact has multiple mappings of course to role. So using the previous example, Alex Yeoh would be shown with `(CS2101, TA)  (CS2103T, TA)  (MA2001, STUDENT)...`. 

This can still be less reader friendly depending on how many courses a person is associated with. This also makes the add command more complex/confusing for users and our logic side too since now both sides need to ensure that:
- the number of roles and courses are similar
- there isn't duplicated courses
- whether or not we allow a person to be a professor for one module but is a student of another
- other problems in regards to editing each contact (such as if the user wants to add another course-role mapping to an existing person, or they want to edit a specific course-role mapping).

I might need everyone's opinions on this. @AY2324S2-CS2103T-T11-2/developers

**Comment by LargeCrowd** [comment]
I would think 1 is better for now as its simpler. Its not optimised but IMO thats ok

**Comment by E0735389** [comment]
Of course 2. Assume each person is either prof of ≤ 2 courses, or TA of ≤ 2 courses and classmate of ≤ 5 courses, it seems entirely reasonable.

Especially if it's abbreviated to "(TA of CS3230, student in CS2103T, CS2101, CS4234, CS4231, CS4261)" or something like that. (Very extreme case.)

**Comment by Hibeom0929** [comment]
I also think the second option would be preferred. As Hong Duc mentioned above, there will not be many courses assigned to one person, and also since the user updates the data, the user may only note the person's course related to him/her, so I think not many courses would be noted.
